import { Injectable } from "@angular/core";

@Injectable({
    providedIn: 'root'
})
export class AppStrings {

    appStrings = {
        manageImport: 'Manage Import',
        home: 'Home',
        newImport: 'New Import',
        import: 'Import',
        importDate: 'Import Date',
        enterDateText: 'Please enter date.',
        amount: 'Amount',
        enterAmountText: 'Please enter amount.',
        description: 'Description',
        close: 'Close',
        manageSales: 'Manage Sale',
        newSale: 'New Sale',
        addSale: 'Add Sale',
        sellingDate: 'Selling Date',
        actualPrice: 'Actual Price',
        sellingPrice: 'Selling Price',
        enterActualPrice: 'Please enter actual price.',
        enterSellingPrice: 'Please enter sale price.',
        profit: 'Profit',
        enterProfit: 'Please enter profit.',
        updateSale: 'Update Sale',
        manageCredit: 'Manage Credit',
        newCredit: 'New Credit',
        addCredit: 'Add Credit',
        updateCredit: 'Update Credit',
        creditDate: 'Credit Date',
        creditDateWarningText: 'Please select date.',
        customerName: 'Customer Name',
        customerNameWarningText: 'Please enter customer name.',
        productPrice: 'Product Price',
        productPriceText: 'Please enter product price.',
        paidAmount: 'Paid Amount',
        paidAmountWarningText: 'Please enter paid amount.',
        remainingAmount: 'Remaining Amount',
        remainingAmountWarningText: 'Please enter remaining amount.',
        manageReciept: 'Manage Receipt',
        newReciept: 'New Receipt',
        filterPlaceholder: 'Type here to search...',
        addReceipt: 'Add Receipt',
        brandName: 'KHAN fashio-hub',
        address: 'Address',
        addressText: '13b/12 Ganeshpuri, mehrun linking road, mehrun, jalgaon - 425001',
        emailId: 'Email Id',
        email: 'zakariyakhan1@gmail.com',
        mobileNumber: 'Mobile Number',
        name: 'Name',
        contactNo: ' +91 8855859341',
        date: 'Date',
        invoice: 'INVOICE',
        total: 'Total',
        rupeesInWords: 'Rupees in Words',
        gstPercent: 'GST (%)',
        taxableAmount: ' Taxable Amount',
        cgstAmount: ' CGST Amount',
        sgstAmount: 'SGST Amount',
        igstAmount: 'IGST Amount',
        totalAmountGST: 'Total Amount GST',
        packing: 'Packing',
        grandTotal: 'Total Amt. [Incl. GST]',
        print: 'Print',
        back: 'Back',
        receiptDate: 'Receipt Date',
        mobile: 'Mobile',
        gst: 'GST',
        cgst: 'CGST',
        sgst: 'SGST',
        selectProduct: 'Select Product',
        quantity: 'Quantity',
        rate: 'Rate',
        add: 'Add',
        receiptWarningText:'Please enter receipt name.',
        optionPlaceholder:'Please select option',
        manageProduct:'Manage Product',
        newProduct:'New Product',
        addProduct:'Add Product',
        updateProduct:'Update Product',
        productNameWarningText:' Please enter product name.',
        price:'Price',
        priceWarningText:'Please enter price.',
        selectImage:'Select Image',
        selectImageWarningText:'Please select file.',
        save:'Save',
        removeImage:'Remove Image',
    }
}